services:
  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9990:9990
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0-oracle
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=abtest
      - MYSQL_ROOT_PASSWORD=robin
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql